//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuneUp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TuneUp.Properties.Resources.en-US", typeof(Resources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as CSV.
        /// </summary>
        public static string Button_ExportCsv {
            get {
                return ResourceManager.GetString("Button_ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as JSON.
        /// </summary>
        public static string Button_ExportJson {
            get {
                return ResourceManager.GetString("Button_ExportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run All.
        /// </summary>
        public static string Button_RunAll {
            get {
                return ResourceManager.GetString("Button_RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show groups.
        /// </summary>
        public static string Button_ShowGroups {
            get {
                return ResourceManager.GetString("Button_ShowGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TuneUp.
        /// </summary>
        public static string Button_ShowTuneUp {
            get {
                return ResourceManager.GetString("Button_ShowTuneUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TuneUp.
        /// </summary>
        public static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Header_ExecutionOrder {
            get {
                return ResourceManager.GetString("Header_ExecutionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution time (ms).
        /// </summary>
        public static string Header_ExecutionTime {
            get {
                return ResourceManager.GetString("Header_ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_DefaultDisplayGroupName {
            get {
                return ResourceManager.GetString("Label_DefaultDisplayGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Label_DefaultExecutionTime {
            get {
                return ResourceManager.GetString("Label_DefaultExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title &lt;Double click here to edit group title&gt;.
        /// </summary>
        public static string Label_DefaultGroupName {
            get {
                return ResourceManager.GetString("Label_DefaultGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution time.
        /// </summary>
        public static string Label_ExecutionTime {
            get {
                return ResourceManager.GetString("Label_ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph execution time (ms).
        /// </summary>
        public static string Label_GraphExecutionTime {
            get {
                return ResourceManager.GetString("Label_GraphExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string Label_GroupNodePrefix {
            get {
                return ResourceManager.GetString("Label_GroupNodePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group total.
        /// </summary>
        public static string Label_GroupTotalExecutionTime {
            get {
                return ResourceManager.GetString("Label_GroupTotalExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Label_Latest {
            get {
                return ResourceManager.GetString("Label_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest run.
        /// </summary>
        public static string Label_LatestRun {
            get {
                return ResourceManager.GetString("Label_LatestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not executed.
        /// </summary>
        public static string Label_NotExecuted {
            get {
                return ResourceManager.GetString("Label_NotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Label_Previous {
            get {
                return ResourceManager.GetString("Label_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous run.
        /// </summary>
        public static string Label_PreviousRun {
            get {
                return ResourceManager.GetString("Label_PreviousRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Label_Total {
            get {
                return ResourceManager.GetString("Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is currently in use by another application. Please close the file before trying to overwrite it..
        /// </summary>
        public static string Message_FileInUse {
            get {
                return ResourceManager.GetString("Message_FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to write the file: {0}.
        /// </summary>
        public static string Message_FileWriteError {
            get {
                return ResourceManager.GetString("Message_FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File in Use.
        /// </summary>
        public static string Title_FileInUse {
            get {
                return ResourceManager.GetString("Title_FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution order..
        /// </summary>
        public static string ToolTip_ExecutionOrder {
            get {
                return ResourceManager.GetString("ToolTip_ExecutionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time it took to execute the node in milliseconds. Values between 0 and 1 are rounded up to 1 ms..
        /// </summary>
        public static string ToolTip_ExecutionTime {
            get {
                return ResourceManager.GetString("ToolTip_ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes that are not executed in the latest run because they had no change. To re-execute, press Run All..
        /// </summary>
        public static string ToolTip_NotExecuted {
            get {
                return ResourceManager.GetString("ToolTip_NotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original node name:
        ///{0}.
        /// </summary>
        public static string ToolTip_OriginalName {
            get {
                return ResourceManager.GetString("ToolTip_OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute entire graph, including nodes with no change since the latest run..
        /// </summary>
        public static string ToolTip_RunAll {
            get {
                return ResourceManager.GetString("ToolTip_RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined execution time of latest and previous run..
        /// </summary>
        public static string ToolTip_TotalExecutionTime {
            get {
                return ResourceManager.GetString("ToolTip_TotalExecutionTime", resourceCulture);
            }
        }
    }
}
