version: 2.0.5
pipeline_os: windows

env:
  - GITHUB_ACCESS_TOKEN_ID: github_access_token_acsbuildguy
  - JENKINS_NODE_WIN: CDA-VS22-DT

code_analysis:
  sonarqube:
    source_encoding: UTF-8
    src: .
    useCommonSonar: true
    coverage_reports:
      - coverage.info

build:
  -
    scripts:
      - dotnet msbuild TuneUp.sln -p:Configuration=Release -restore

deployment:
  -
    type: sign
    files_to_sign:
      - TuneUp/dist/TuneUp/bin/TuneUp.dll
      - TuneUp/dist/TuneUp/bin/en-US/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/en-GB/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/cs-CZ/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/de-DE/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/es-ES/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/fr-FR/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/it-IT/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/ja-JP/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/ko-KR/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/pl-PL/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/pt-BR/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/ru-RU/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/zh-CN/TuneUp.resources.dll
      - TuneUp/dist/TuneUp/bin/zh-TW/TuneUp.resources.dll
  -
    type: customized
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -Command Compress-Archive -Path 'TuneUp/dist/TuneUp/*' -DestinationPath 'TuneUp.zip'"
  -
    type: artifacts
    publish_to_jenkins: true
    publish_to_artifactory: false
    publish_to_package_manager: true
    use_dev_pm: false
    outputs:
      - TuneUp.zip
