version: 2.0.1
pipeline_os: windows
create_pr_release_to_master: true

env:
  - GITHUB_ACCESS_TOKEN_ID: github_access_token_acsbuildguy
  - JENKINS_NODE_WIN: CDA-VS22-SVC

code_analysis:
  sonarqube:
    source_encoding: UTF-8
    src: .
    coverage_reports:
      - coverage.info

build:
  -
    scripts:
      - dotnet msbuild TuneUp.sln -p:Configuration=Release -restore

deployment:
  -
    type: sign
    files_to_sign:
      - TuneUp/bin/Release/net8.0-windows/TuneUp.dll
      - TuneUp/bin/Release/net8.0-windows/en-US/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/en-US/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/cs-CZ/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/de-DE/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/es-ES/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/fr-FR/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/it-IT/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/ja-JP/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/ko-KR/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/pl-PL/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/pt-BR/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/ru-RU/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/zh-CN/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/zh-Hans/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/zh-Hant/TuneUp.resources.dll
      - TuneUp/bin/Release/net8.0-windows/zh-TW/TuneUp.resources.dll
  -
    type: customized
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -Command Compress-Archive -Path 'TuneUp/dist/TuneUp/*' -DestinationPath 'TuneUp.zip'"
  -
    type: artifacts
    publish_to_jenkins: true
    publish_to_artifactory: false
    publish_to_package_manager: true
    allow_branches: ".*"
    outputs:
      - TuneUp.zip