name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout TuneUp Repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          path: TuneUp
      - name: Checkout Dynamo Repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          path: Dynamo
      - name: Setup Nuget
        uses: nuget/setup-nuget@a21f25cd3998bf370fde17e3f1b4c12c175172f9 # v2.0.0
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
      - name: Install dependencies for Dynamo solution
        run: nuget restore ${{ github.workspace }}\Dynamo\src\Dynamo.All.sln
      - name: Install dependencies for TuneUp solution
        run: nuget restore ${{ github.workspace }}\TuneUp\TuneUp.sln
      - name: Build Dynamo solution
        run: msbuild ${{ github.workspace }}\Dynamo\src\Dynamo.All.sln
      - name: Build TuneUp solution
        run: msbuild ${{ github.workspace }}\TuneUp\TuneUp.sln
      - name: Look for TuneUp.dll
        run: |
          Write-Output "***Locating TuneUp.dll!***"
          if (Test-Path -Path "${{ github.workspace }}\TuneUp\TuneUp\bin\Debug") {
            Write-Output "TuneUp.dll exists!"
          } else {
            Write-Error "TuneUp.dll was not found!"
          }
