# Build Tuneup using latest VS and DotNET
name: Tuneup-Build
on: [push]
jobs:
 build:
  runs-on: windows-latest
  steps:
    - name: Checkout TuneUp Repo
      uses: actions/checkout@v2
      with:
        path: TuneUp
    - name: Checkout Dynamo Repo
      uses: actions/checkout@v2
      with:
        path: Dynamo
        repository: DynamoDS/Dynamo
        ref: RC2.5.0_master
    - name: Setup Nuget.exe to use on VM
      uses: nuget/setup-nuget@v1
    - name: Nuget Restore in Dynamo solution
      run: nuget restore $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    - name: Nuget Restore in TuneUp solution
      run: nuget restore $Env:GITHUB_WORKSPACE\TuneUp\TuneUp.sln
    - name: Build Dynamo with MSBuild
      run: |
        echo "***Execute ls, and you should see two folders created***"
        ls
        echo "***Continue with the build, Good luck developer!***
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    - name: Build TuneUp with DotNET
      run: |
        echo "***Building Tuneup now following Dynamo build***"
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\TuneUp\TuneUp.sln
    # look for TuneUp
    - name: find TuneUp
      run: |
        ls "%GITHUB_WORKSPACE%\TuneUp\TuneUp\bin\Debug"