# Build Tuneup using latest VS and DotNET
name: Tuneup-Build
on: [push]
jobs:
 build:
  runs-on: windows-latest
  steps:
    - name: Checkout TuneUp
      uses: actions/checkout@v2
      with:
        path: TuneUp
    - name: Checkout Dynamo repo
      uses: actions/checkout@v2
      with:
        path: Dynamo
        repository: DynamoDS/Dynamo
        ref: RC2.5.0_master
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
    - name: Nuget Restore in Dynamo solution
      run: nuget restore $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    - name: Build Dynamo with DotNET
      run: |
        echo "ls"
        ls
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    - name: Build TuneUp with DotNET
      run: |
        echo "ls"
        ls
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\TuneUp\TuneUp.sln
    # look for TuneUp
    - name: find TuneUp
      run: |
        ls "%GITHUB_WORKSPACE%\TuneUp\bin\Debug"